### ISSUE TITLE
feat: alertmanager config

### ISSUE THREAD

**Issue by caerulescens** [generic-infrastructure/template-app-fastapi#3]
```yaml
route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 30m
  group_by: [ alertname ]

receivers:
  - name: 'default-receiver'
```
