### ISSUE TITLE
chore: add datasources config 

### ISSUE THREAD

**Issue by caerulescens** [generic-infrastructure/template-app-fastapi#4]
```yaml
apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: true
    name: loki
    type: loki
    uid: loki
    url: http://loki-gateway
    version: 1

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 1

  - name: Tempo
    type: tempo
    access: proxy
    url: http://query-frontend:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

```
